#!/bin/bash
echo "🔧 Injecting Supabase environment variables..."

# Verify environment variables exist
if [ -z "$SUPABASE_URL" ]; then
  echo "❌ SUPABASE_URL environment variable not found"
  exit 1
fi

if [ -z "$SUPABASE_ANON_KEY" ]; then
  echo "❌ SUPABASE_ANON_KEY environment variable not found"
  exit 1
fi

# Create supabase-config.js with real environment variables
cat > supabase-config.js << CONFIGEOF
// Supabase Configuration - Generated by Render at build time
// Environment variables injected at build time

const supabaseConfig = {
  url: '${SUPABASE_URL}',
  anonKey: '${SUPABASE_ANON_KEY}',
  
  // Edge Function URLs
  functions: {
    openai: '${SUPABASE_URL}/functions/v1/openai-proxy',
    replicate: '${SUPABASE_URL}/functions/v1/replicate-proxy'
  }
};

// Export for use in main app
window.supabaseConfig = supabaseConfig;
console.log('🔧 Supabase config loaded with URL:', supabaseConfig.url);
CONFIGEOF

echo "✅ Supabase config created with environment variables"
echo "📦 Config file size: $(wc -c < supabase-config.js) bytes"
echo "🔍 Config created successfully (credentials not logged for security)"
